# Generated by Django 4.1.2 on 2022-11-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10, null=True)),
                ('date', models.DateField()),
                ('cl', models.CharField(max_length=10)),
                ('present_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='school', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('joindate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtra_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('class_belong', models.CharField(choices=[('Waec Class', 'Waec Class'), ('Jamb Class', 'Jamb Class'), ('Putme Class', 'Putme Class'), ('School of Nursing Class', 'School of Nursing Class'), ('Art Class', 'Art Class'), ('Commercial Class', 'Commercial Class'), ('Private Class', 'Private Class')], default='Waec Class', max_length=200)),
                ('choice_of_course', models.CharField(max_length=200)),
                ('personal_mobile', models.CharField(max_length=11, null=True)),
                ('fee_paid', models.PositiveIntegerField(null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('parent_or_gaurdian_mobile', models.CharField(max_length=11, null=True)),
                ('Parent_gaurdian_name', models.CharField(max_length=200)),
                ('permanent_address', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('date_of_birth', models.DateTimeField(blank=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('choices_unversity_son', models.CharField(max_length=40)),
                ('hear_about_us', models.CharField(choices=[('Social Media', 'Social Media'), ('Friend', 'Friend'), ('Parents or Gaurdian', 'Parents or Gaurdian')], default='Social Media', max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
