# Generated by Django 4.1.2 on 2022-11-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra_1',
            name='special_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
