# Generated by Django 4.1.2 on 2022-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_studentextra_1_special_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra_1',
            name='special_needs',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
