# Generated by Django 4.1.2 on 2022-11-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0003_alter_studentextra_1_special_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExtra_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_type', models.CharField(max_length=10)),
                ('teacher_sex', models.CharField(max_length=10)),
                ('salary', models.PositiveIntegerField()),
                ('joindate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=40)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/teachers/')),
                ('address', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('teacher_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherExtra',
        ),
    ]
