# Generated by Django 4.1.2 on 2022-11-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacherextra_1_delete_teacherextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra_1',
            name='teacher_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200),
        ),
    ]
