# Generated by Django 4.1.2 on 2022-11-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_teacherextra_1_teacher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra_1',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
