# Generated by Django 4.1.2 on 2022-11-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_teacherextra_1_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra_1',
            name='teacher_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/teachers/'),
        ),
    ]
