# Generated by Django 4.1.2 on 2022-11-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_teacherextra_1_teacher_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='studentextra_1',
            name='class_belong',
        ),
        migrations.AddField(
            model_name='studentextra_1',
            name='cl',
            field=models.CharField(choices=[('Waec Class', 'Waec Class'), ('Jamb Class', 'Jamb Class'), ('Putme Class', 'Putme Class'), ('School of Nursing Class', 'School of Nursing Class'), ('Art Class', 'Art Class'), ('Commercial Class', 'Commercial Class'), ('Private Class', 'Private Class')], default='Waec Class', max_length=200),
        ),
    ]
