# Generated by Django 4.1.2 on 2022-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_attendance_roll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra_1',
            name='roll',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
