# Generated by Django 4.1.2 on 2022-11-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_studentextra_1_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra_1',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='teacherextra_1',
            name='teacher_picture',
            field=models.ImageField(upload_to='images/teachers/'),
        ),
    ]
